"""Emit the per-stage reconciliation table used as cost-model evidence.

``tmp_analysis/reconcile.py`` writes, per plan, one ``.model.json`` (the
per-record term every stage contributes to the objective) and one
``.measured.json`` (wall-clock trace of the same plan).  This script turns
those pairs into

  * ``my_paper/<paper>/tables/stage_reconcile.tex`` (booktabs, ready to
    ``\\input``),
  * ``outputs/cost_model_reconcile_20260913/stage_reconcile.md`` and ``.csv``
    for reading and for artifact review.

Usage (inside the container):
  python -u tmp_analysis/make_stage_reconcile_table.py
"""

import csv
import json
from pathlib import Path

ROOT = Path("/workspace/OptimalCedar")
RECON = ROOT / "tmp_analysis/reconcile"
OUT = ROOT / "outputs/cost_model_reconcile_20260913"
PAPER = ROOT / "my_paper/69e75a0100d7b4afeb1cfc20/tables"
# Records every reconciled plan processed (``CEDAR_RECONCILE_SAMPLES``).
RECORDS = 1000

# Plan order is the measured order (fastest first); the label carries the
# worker count the plan was executed with.
PLANS = [
    ("pico", "PICO (ours)", 8),
    ("plumber", "Plumber-style", 32),
    ("cedar", "Cedar", 32),
    ("unoptimized", "Unoptimized", 8),
    ("raydata", "Ray Data", 8),
]

OP_NAMES = {
    0: "batch",
    1: "norm",
    2: "blur",
    3: "gray",
    4: "jitter",
    5: "hflip",
    6: "crop",
    7: "tofloat",
    8: "read",
}

# LaTeX-safe spelling of the same names (``_`` is escaped for text mode).
OP_NAMES_TEX = dict(OP_NAMES)
OP_NAMES_TEX[7] = "to\\_float"

BACKENDS = {
    "INPROCESS": "INP",
    "SMP": "SMP",
    "RAY": "RAY",
    "TF_RAY": "TFR",
    "CUDA": "GPU",
}


def stage_name(row) -> str:
    ops = "+".join(OP_NAMES_TEX.get(int(p), str(p)) for p in row["ops"])
    return f"\\#{row['stage_pipe']} {ops}"


def load(plan: str) -> dict:
    model = json.loads((RECON / f"{plan}.model.json").read_text())
    measured = json.loads((RECON / f"{plan}.measured.json").read_text())
    stats = measured.get("stage_statistics", {})
    services = measured.get("service_stats", {})
    rows = []
    local = smp = gpu = 0.0
    for row, pid in zip(model["rows"], model["stages"]):
        stage = stats.get(str(pid), {})
        service = services.get(str(pid)) or {}
        term = row["charged"]
        if row["variant"] in ("RAY", "TF_RAY", "INPROCESS"):
            local += term
        elif row["variant"] == "SMP":
            smp = max(smp, term)
        else:
            gpu += term
        service_ms = service.get("mean_ms_per_sample")
        rows.append(
            {
                "pipe": int(pid),
                "stage_pipe": int(pid),
                "ops": row["ops"],
                "backend": BACKENDS.get(row["variant"], row["variant"]),
                "variant": row["variant"],
                "width": int(row["width"]),
                "model": float(term),
                "compute_per_width": row["compute"] / max(1, row["width"]),
                "boundary": row["boundary_local"] + row["boundary_external"],
                "window_mb": row["window_bytes"] / 1e6,
                "cross_host_floor": row["cross_host_floor"],
                "measured_service": (
                    float(service_ms) if service_ms is not None else None
                ),
                "measured_latency": (
                    float(stage.get("median_ms"))
                    if stage.get("median_ms") is not None
                    else None
                ),
            }
        )
    return {
        "plan": plan,
        "workers": None,
        "score": max(local, smp, gpu),
        "local": local,
        "smp": smp,
        "gpu": gpu,
        "total_time_sec": measured.get("total_time_sec"),
        "rows": rows,
    }


def per_plan(plan: str, workers: int) -> dict:
    data = load(plan)
    data["workers"] = workers
    data["measured_lane"] = (
        data["total_time_sec"] * 1000.0 / RECORDS * workers
        if data["total_time_sec"]
        else None
    )
    return data


def tex_table(plans) -> str:
    lines = [
        "% Generated by tmp_analysis/make_stage_reconcile_table.py",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\small",
        "  \\caption{Per-stage reconciliation of the cost model against the",
        "  executed plan on the SimCLRv2 workload (1000 records, batch 4, one",
        "  shared profile; each plan runs at the worker count its own planner",
        "  chooses).  \\emph{Comp.} is the per-record operator cost at the",
        "  stage's width, which is directly comparable with \\emph{meas.}, the",
        "  service the stage's own backend reports for the same records",
        "  (worker-side for \\textsc{inp}, process-side for \\textsc{smp},",
        "  actor-side for \\textsc{ray}).  \\emph{Stage} is the term the",
        "  objective charges for the stage --- operator compute plus boundaries",
        "  and, for \\textsc{ray}, the cross-host payload budget --- and",
        "  \\emph{lat.} is the traced per-record residence at that stage, which",
        "  additionally contains the delay behind the stage's prefetch window.",
        "  Each plan block ends with the plan-level objective against the",
        "  measured end-to-end time.}",
        "  \\label{tab:stage-reconcile}",
        "  \\begin{tabular}{llrrrrrr}",
        "    \\toprule",
        "    Stage & Backend & Comp. & Meas. & $\\Delta$ & Stage & Lat. \\\\",
        "    & (width) & (ms) & (ms) & (comp./meas.) & (ms) & (ms) \\\\",
        "    \\midrule",
    ]
    for entry in plans:
        label = next(
            (name for key, name, _ in PLANS if key == entry["plan"]), entry["plan"]
        )
        ratio = (
            entry["measured_lane"] / entry["score"]
            if entry["measured_lane"]
            else float("nan")
        )
        lines.append(
            "    \\multicolumn{7}{l}{\\emph{%s plan}: W=%d, model %.2f vs "
            "measured %.2f ms/record/worker (%.2f$\\times$)} \\\\"
            % (label, entry["workers"], entry["score"], entry["measured_lane"], ratio)
        )
        for row in entry["rows"]:
            # ``Meas.`` is the backend-reported per-record service, which only
            # parallel backends expose; the synchronous local chain is checked
            # against the isolated operator sweep in the calibration layer, so
            # its ratio is left blank here and only its traced residence is
            # reported.
            parallel = row["backend"] in ("SMP", "RAY", "TFR", "GPU")
            service = (
                row["measured_service"] / max(1, row["width"])
                if parallel and row["measured_service"] is not None
                else None
            )
            latency = row["measured_latency"]
            comp = (
                row["compute_per_width"] if parallel else row["model"]
            )
            delta = comp / service if service else None
            lines.append(
                "    \\quad %s & %s (%d) & %.2f & %s & %s & %.2f & %s \\\\"
                % (
                    stage_name(row),
                    row["backend"],
                    row["width"],
                    comp,
                    f"{service:.2f}" if service is not None else "--",
                    f"{delta:.2f}" if delta is not None else "--",
                    row["model"],
                    f"{latency:.2f}" if latency is not None else "--",
                )
            )
        lines.append("    \\addlinespace")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table*}",
        "",
    ]
    return "\n".join(lines)


def markdown(plans) -> str:
    out = []
    for entry in plans:
        ratio = (
            entry["measured_lane"] / entry["score"]
            if entry["measured_lane"]
            else float("nan")
        )
        out.append(
            f"### {entry['plan']} (W={entry['workers']}): model "
            f"{entry['score']:.2f} vs measured {entry['measured_lane']:.2f} "
            f"ms/record/worker ({ratio:.2f}x)"
        )
        out.append("")
        out.append(
            "| stage | backend (w) | comp. (ms) | meas. (ms) | delta | "
            "stage term (ms) | stage lat. (ms) | window (MB) |"
        )
        out.append("|---|---|---|---|---|---|---|---|")
        for row in entry["rows"]:
            parallel = row["backend"] in ("SMP", "RAY", "TFR", "GPU")
            measured = (
                row["measured_service"] / max(1, row["width"])
                if parallel and row["measured_service"] is not None
                else None
            )
            comp = row["compute_per_width"] if parallel else row["model"]
            delta = comp / measured if measured else None
            out.append(
                "| #{pipe} {ops} | {backend} ({width}) | {comp:.2f} | {meas} | "
                "{delta} | {model:.2f} | {lat} | {win:.1f} |".format(
                    pipe=row["pipe"],
                    ops="+".join(
                        OP_NAMES.get(int(p), str(p)) for p in row["ops"]
                    ),
                    backend=row["backend"],
                    width=row["width"],
                    comp=comp,
                    meas=(
                        f"{measured:.2f}" if measured is not None else "--"
                    ),
                    delta=f"{delta:.2f}" if delta is not None else "--",
                    model=row["model"],
                    lat=(
                        f"{row['measured_latency']:.2f}"
                        if row["measured_latency"] is not None
                        else "--"
                    ),
                    win=row["window_mb"],
                )
            )
        out.append("")
    return "\n".join(out)


def main() -> None:
    plans = [per_plan(plan, workers) for plan, _, workers in PLANS]
    OUT.mkdir(parents=True, exist_ok=True)
    PAPER.mkdir(parents=True, exist_ok=True)
    (PAPER / "stage_reconcile.tex").write_text(tex_table(plans))
    (OUT / "stage_reconcile.md").write_text(markdown(plans))
    with (OUT / "stage_reconcile.csv").open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "plan",
                "workers",
                "stage_pipe",
                "ops",
                "backend",
                "width",
                "model_ms",
                "measured_service_ms",
                "measured_latency_ms",
                "window_mb",
                "cross_host_floor_ms",
            ]
        )
        for entry in plans:
            for row in entry["rows"]:
                writer.writerow(
                    [
                        entry["plan"],
                        entry["workers"],
                        row["pipe"],
                        "|".join(str(p) for p in row["ops"]),
                        row["backend"],
                        row["width"],
                        round(row["model"], 4),
                        (
                            round(row["measured_service"], 4)
                            if row["measured_service"] is not None
                            else ""
                        ),
                        (
                            round(row["measured_latency"], 4)
                            if row["measured_latency"] is not None
                            else ""
                        ),
                        round(row["window_mb"], 2),
                        (
                            round(row["cross_host_floor"], 4)
                            if row["cross_host_floor"] is not None
                            else ""
                        ),
                    ]
                )
    (OUT / "stage_reconcile.json").write_text(json.dumps(plans, indent=2))
    print("wrote", PAPER / "stage_reconcile.tex")
    print("wrote", OUT / "stage_reconcile.md")
    print(markdown(plans))


if __name__ == "__main__":
    main()
