#!/usr/bin/env bash
# Repeats of the operator-order transfer experiment.
#
# The first run measured each order once, which is too noisy to claim that an
# operator in an unchanged position (the ImageReader) costs the same in every
# pipeline.  This script reuses the plans generated by
# run_unopt_order_transfer_20260921.sh and runs every order R times in
# round-robin order, keeping one reconcile trace per repeat.
set -uo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO" || exit 1
source "$REPO/env/bin/activate"

SOURCE_RUN=${SOURCE_RUN:-outputs/unopt_order_transfer_20260921}
RUN=${RUN:-outputs/unopt_order_transfer_repeats_20260921}
REPEATS=${REPEATS:-3}
PROFILE=outputs/ultimate_eight_optimizers_20260920/simclrv2/profiles/shared.yaml
DATASET=evaluation/pipelines/simclrv2/cedar_dataset.py
TRAIN=evaluation/datasets/imagenette2/imagenette2/train
RAY_IP=172.23.166.105:6379

mkdir -p "$RUN"/{plans,logs,results}
cp -n "$SOURCE_RUN"/plans/*.yaml "$RUN/plans/" 2>/dev/null || true

export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 \
       NUMEXPR_NUM_THREADS=1 HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
       CEDAR_RAY_PLACEMENT_RESOURCE=cedar_remote CEDAR_RAY_REQUIRE_REMOTE=1 \
       CEDAR_WORKER_READY_TIMEOUT_SEC=600

for rep in $(seq 1 "$REPEATS"); do
  for cell in declared pico cedar old-dp; do
    tag="${cell}_r${rep}"
    echo "RUN $tag"
    rm -rf "$RUN/reconcile_$tag"
    mkdir -p "$RUN/reconcile_$tag"
    CEDAR_RECONCILE_DIR="$REPO/$RUN/reconcile_$tag" \
    python -u scripts/run_fixed_plan_throughput.py \
      --plan "$RUN/plans/${cell}.yaml" \
      --label "order-${cell}-r${rep}" \
      --results-path "$RUN/results/${tag}.json" \
      --dataset-file "$DATASET" \
      --dataset-kwargs "dataset_path=$REPO/$TRAIN" \
      --batch-size 4 --num-epochs 1 --num-total-samples 0 \
      --profiled-stats "$PROFILE" --ray-ip "$RAY_IP" \
      > "$RUN/logs/${tag}.log" 2>&1
    tail -1 "$RUN/logs/${tag}.log"
  done
done
echo DONE
